import { chromium } from 'playwright-chromium'
import { mkdirSync, writeFileSync } from 'node:fs'
import assert from 'node:assert/strict'
const browser = await chromium.launch({ executablePath: process.env.SLIDEV_BROWSER_PATH || '/Applications/Yandex.app/Contents/MacOS/Yandex', headless: true })
const page = await browser.newPage({ viewport: { width: 1280, height: 720 }, deviceScaleFactor: 1 })
const errors = [], failures = [], report = []
page.on('pageerror', e => errors.push(String(e)))
page.on('response', r => { if (r.status() >= 400) failures.push([r.status(), r.url()]) })
mkdirSync('output/qa', { recursive: true })
async function go(n, suffix = '') {
  await page.goto(`http://localhost:3031/${n}${suffix}`, { waitUntil: 'networkidle' })
  await page.evaluate(() => document.fonts.ready)
  await page.mouse.move(1250, 680)
  return page.locator('[data-demo]:visible')
}
async function snapshot(name) {
  const demo = page.locator('[data-demo]:visible')
  const overflow = await demo.evaluate(el => {
    const layout = el.closest('.slidev-layout').getBoundingClientRect()
    const scale = layout.width / 1280
    return [...el.querySelectorAll('button, svg.binary-image, .demo-note, .demo-takeaway, table, .kl-settings, .ar-factors')]
      .filter(e => e.getBoundingClientRect().width > 0)
      .map(e => ({ text: e.textContent.slice(0, 80), rect: e.getBoundingClientRect().toJSON() }))
      .filter(e => e.rect.bottom > layout.top + 673 * scale || e.rect.right > layout.right - 30 * scale)
  })
  assert.deepEqual(overflow, [], `Overflow in ${name}`)
  await page.screenshot({ path: `output/qa/${name}.png` })
  report.push(name)
}
try {
  let demo = await go(29)
  const distributions = new Map()
  for (const n of [10, 100, 1000, 10000, 10]) {
    await demo.getByRole('button', { name: String(n), exact: true }).click()
    assert.equal(await demo.getAttribute('data-sample-size'), String(n))
    assert.equal(await demo.getByRole('button', { name: String(n), exact: true }).getAttribute('aria-pressed'), 'true')
    const bars = await demo.locator('rect').evaluateAll(els => els.map(el => ({ count: Number(el.getAttribute('data-count')), y: Number(el.getAttribute('y')), height: Number(el.getAttribute('height')) })))
    assert.equal(bars.reduce((sum, b) => sum + b.count, 0), n)
    assert.ok(bars.every(b => b.y >= 12 && Math.abs(b.y + b.height - 122) < 1e-10))
    if (distributions.has(n)) assert.deepEqual(bars, distributions.get(n), 'Returning to a size preserves its data')
    else distributions.set(n, bars)
    assert.equal(new URL(page.url()).pathname, '/29')
    await snapshot(`histogram-n-${n}`)
  }
  for (const [a, b] of [[10, 100], [100, 1000], [1000, 10000]]) {
    assert.ok(distributions.get(a).every((bar, k) => bar.count <= distributions.get(b)[k].count), 'Samples must be nested')
  }
  await demo.getByRole('button', { name: 'Reset', exact: true }).click()
  const initial = await demo.locator('.histogram-readout').innerText()
  await demo.getByRole('button', { name: 'Sample', exact: true }).click()
  const first = await demo.locator('.histogram-readout').innerText()
  assert.notEqual(first, initial)
  assert.equal(await demo.locator('rect[fill="#e17838"]').count(), 1)
  assert.equal(new URL(page.url()).pathname, '/29')
  await demo.getByRole('button', { name: 'Reset', exact: true }).click()
  assert.equal(await demo.locator('.histogram-readout').innerText(), initial)
  await demo.getByRole('button', { name: 'Sample', exact: true }).click()
  assert.equal(await demo.locator('.histogram-readout').innerText(), first)
  await snapshot('histogram-compact')
  for (let i = 0; i < 4; i++) await page.keyboard.press('ArrowRight')
  await page.waitForURL('**/30')
  await page.keyboard.press('ArrowLeft')
  await page.waitForURL('**/29?clicks=3')
  assert.equal(await demo.locator('.histogram-readout').innerText(), first, 'Preserve sample on slide return')
  await snapshot('histogram-final-reveal')

  demo = await go(39)
  await demo.getByRole('button', { name: 'Next pixel', exact: true }).click()
  const firstContext = await demo.locator('.ar-context').innerText()
  await demo.getByRole('button', { name: 'Generate', exact: true }).click()
  assert.equal(await demo.locator('.ar-context').innerText(), firstContext, 'Active mode must not restart the example')
  await snapshot('ar-first-pixel')
  for (let j = 1; j < 9; j++) await demo.getByRole('button', { name: 'Next pixel', exact: true }).click()
  assert.equal(await demo.getByRole('button', { name: 'Next pixel', exact: true }).isDisabled(), true)
  assert.equal(await demo.locator('.ar-factors b').count(), 9)
  await snapshot('ar-complete')
  await demo.getByRole('button', { name: 'Evaluate', exact: true }).click()
  for (let j = 0; j < 9; j++) await demo.getByRole('button', { name: 'Next pixel', exact: true }).click()
  assert.match(await demo.locator('.ar-total').innerText(), /p\(image\)/)
  await snapshot('ar-evaluate')
  const evaluated = await demo.locator('.ar-image svg').innerHTML()
  await demo.getByRole('button', { name: 'Another image', exact: true }).click()
  assert.notEqual(await demo.locator('.ar-image svg').innerHTML(), evaluated)
  assert.equal(await demo.locator('.ar-context').innerText(), 'Context: empty')
  assert.equal(await demo.getByRole('button', { name: 'Evaluate', exact: true }).getAttribute('aria-pressed'), 'true')
  await demo.getByRole('button', { name: 'Generate', exact: true }).click()
  await demo.getByRole('button', { name: 'Next pixel', exact: true }).click()
  await demo.getByRole('button', { name: 'Start over', exact: true }).click()
  assert.equal(await demo.locator('.ar-context').innerText(), 'Context: empty')
  assert.ok((await demo.locator('.ar-factors b').allTextContents()).every(x => x === '—'))
  assert.equal(await demo.getByRole('button', { name: 'Next pixel', exact: true }).isEnabled(), true)
  assert.deepEqual(await demo.locator('button').allTextContents(), ['Generate', 'Evaluate', 'Next pixel', 'Start over'])
  assert.equal(new URL(page.url()).pathname, '/39')
  await snapshot('ar-start-over')

  // Pointer interaction must still work while annotation mode is enabled.
  demo = await go(29, '?tools')
  const toolbar = page.getByRole('navigation', { name: 'Lecture annotation tools' })
  await toolbar.getByRole('button', { name: 'Pen', exact: true }).click()
  await demo.getByRole('button', { name: 'Sample', exact: true }).click()
  assert.equal(await demo.locator('rect[fill="#e17838"]').count(), 1)
  assert.equal(new URL(page.url()).pathname, '/29')
  await snapshot('histogram-with-pen')
  await page.mouse.move(450, 510)
  await page.mouse.down()
  await page.mouse.move(620, 515, { steps: 12 })
  await page.mouse.up()
  assert.equal(await toolbar.getByRole('button', { name: 'Undo', exact: true }).isEnabled(), true, 'Pen must still draw outside controls')
  await toolbar.getByRole('button', { name: 'Undo', exact: true }).click()
  await toolbar.getByRole('button', { name: 'Pen', exact: true }).click()
  assert.deepEqual(errors, [])
  assert.deepEqual(failures, [])
  console.log(`Demo interaction checks passed: ${report.length} visual states, reset, keyboard, navigation, pen mode.`)
} finally {
  await page.screenshot({ path: 'output/qa/demos-last-state.png' })
  writeFileSync('output/qa/demos-report.json', JSON.stringify({ report, errors, failures }, null, 2))
  await browser.close()
}
